# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lespag_m/Documents/Tek3/ZIA/local

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lespag_m/Documents/Tek3/ZIA/local

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lespag_m/Documents/Tek3/ZIA/local/CMakeFiles /home/lespag_m/Documents/Tek3/ZIA/local/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lespag_m/Documents/Tek3/ZIA/local/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named zia

# Build rule for target.
zia: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zia
.PHONY : zia

# fast build rule for target.
zia/fast:
	$(MAKE) -f CMakeFiles/zia.dir/build.make CMakeFiles/zia.dir/build
.PHONY : zia/fast

#=============================================================================
# Target rules for targets named CgiModule

# Build rule for target.
CgiModule: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CgiModule
.PHONY : CgiModule

# fast build rule for target.
CgiModule/fast:
	$(MAKE) -f modules/CGIModule/CMakeFiles/CgiModule.dir/build.make modules/CGIModule/CMakeFiles/CgiModule.dir/build
.PHONY : CgiModule/fast

#=============================================================================
# Target rules for targets named PreParseRequest

# Build rule for target.
PreParseRequest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PreParseRequest
.PHONY : PreParseRequest

# fast build rule for target.
PreParseRequest/fast:
	$(MAKE) -f modules/PreParseRequest/CMakeFiles/PreParseRequest.dir/build.make modules/PreParseRequest/CMakeFiles/PreParseRequest.dir/build
.PHONY : PreParseRequest/fast

#=============================================================================
# Target rules for targets named PostGenerateResponse

# Build rule for target.
PostGenerateResponse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PostGenerateResponse
.PHONY : PostGenerateResponse

# fast build rule for target.
PostGenerateResponse/fast:
	$(MAKE) -f modules/PostGenerateResponse/CMakeFiles/PostGenerateResponse.dir/build.make modules/PostGenerateResponse/CMakeFiles/PostGenerateResponse.dir/build
.PHONY : PostGenerateResponse/fast

#=============================================================================
# Target rules for targets named PreConnexion

# Build rule for target.
PreConnexion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PreConnexion
.PHONY : PreConnexion

# fast build rule for target.
PreConnexion/fast:
	$(MAKE) -f modules/PreConnexion/CMakeFiles/PreConnexion.dir/build.make modules/PreConnexion/CMakeFiles/PreConnexion.dir/build
.PHONY : PreConnexion/fast

#=============================================================================
# Target rules for targets named ContentModule

# Build rule for target.
ContentModule: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContentModule
.PHONY : ContentModule

# fast build rule for target.
ContentModule/fast:
	$(MAKE) -f modules/ContentModule/CMakeFiles/ContentModule.dir/build.make modules/ContentModule/CMakeFiles/ContentModule.dir/build
.PHONY : ContentModule/fast

#=============================================================================
# Target rules for targets named PostConnexion

# Build rule for target.
PostConnexion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PostConnexion
.PHONY : PostConnexion

# fast build rule for target.
PostConnexion/fast:
	$(MAKE) -f modules/PostConnexion/CMakeFiles/PostConnexion.dir/build.make modules/PostConnexion/CMakeFiles/PostConnexion.dir/build
.PHONY : PostConnexion/fast

#=============================================================================
# Target rules for targets named PostParseRequest

# Build rule for target.
PostParseRequest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PostParseRequest
.PHONY : PostParseRequest

# fast build rule for target.
PostParseRequest/fast:
	$(MAKE) -f modules/PostParseRequest/CMakeFiles/PostParseRequest.dir/build.make modules/PostParseRequest/CMakeFiles/PostParseRequest.dir/build
.PHONY : PostParseRequest/fast

sources/ConfParser.o: sources/ConfParser.cpp.o
.PHONY : sources/ConfParser.o

# target to build an object file
sources/ConfParser.cpp.o:
	$(MAKE) -f CMakeFiles/zia.dir/build.make CMakeFiles/zia.dir/sources/ConfParser.cpp.o
.PHONY : sources/ConfParser.cpp.o

sources/ConfParser.i: sources/ConfParser.cpp.i
.PHONY : sources/ConfParser.i

# target to preprocess a source file
sources/ConfParser.cpp.i:
	$(MAKE) -f CMakeFiles/zia.dir/build.make CMakeFiles/zia.dir/sources/ConfParser.cpp.i
.PHONY : sources/ConfParser.cpp.i

sources/ConfParser.s: sources/ConfParser.cpp.s
.PHONY : sources/ConfParser.s

# target to generate assembly for a file
sources/ConfParser.cpp.s:
	$(MAKE) -f CMakeFiles/zia.dir/build.make CMakeFiles/zia.dir/sources/ConfParser.cpp.s
.PHONY : sources/ConfParser.cpp.s

sources/Logger.o: sources/Logger.cpp.o
.PHONY : sources/Logger.o

# target to build an object file
sources/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/zia.dir/build.make CMakeFiles/zia.dir/sources/Logger.cpp.o
.PHONY : sources/Logger.cpp.o

sources/Logger.i: sources/Logger.cpp.i
.PHONY : sources/Logger.i

# target to preprocess a source file
sources/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/zia.dir/build.make CMakeFiles/zia.dir/sources/Logger.cpp.i
.PHONY : sources/Logger.cpp.i

sources/Logger.s: sources/Logger.cpp.s
.PHONY : sources/Logger.s

# target to generate assembly for a file
sources/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/zia.dir/build.make CMakeFiles/zia.dir/sources/Logger.cpp.s
.PHONY : sources/Logger.cpp.s

sources/ModuleLoader.o: sources/ModuleLoader.cpp.o
.PHONY : sources/ModuleLoader.o

# target to build an object file
sources/ModuleLoader.cpp.o:
	$(MAKE) -f CMakeFiles/zia.dir/build.make CMakeFiles/zia.dir/sources/ModuleLoader.cpp.o
.PHONY : sources/ModuleLoader.cpp.o

sources/ModuleLoader.i: sources/ModuleLoader.cpp.i
.PHONY : sources/ModuleLoader.i

# target to preprocess a source file
sources/ModuleLoader.cpp.i:
	$(MAKE) -f CMakeFiles/zia.dir/build.make CMakeFiles/zia.dir/sources/ModuleLoader.cpp.i
.PHONY : sources/ModuleLoader.cpp.i

sources/ModuleLoader.s: sources/ModuleLoader.cpp.s
.PHONY : sources/ModuleLoader.s

# target to generate assembly for a file
sources/ModuleLoader.cpp.s:
	$(MAKE) -f CMakeFiles/zia.dir/build.make CMakeFiles/zia.dir/sources/ModuleLoader.cpp.s
.PHONY : sources/ModuleLoader.cpp.s

sources/Server.o: sources/Server.cpp.o
.PHONY : sources/Server.o

# target to build an object file
sources/Server.cpp.o:
	$(MAKE) -f CMakeFiles/zia.dir/build.make CMakeFiles/zia.dir/sources/Server.cpp.o
.PHONY : sources/Server.cpp.o

sources/Server.i: sources/Server.cpp.i
.PHONY : sources/Server.i

# target to preprocess a source file
sources/Server.cpp.i:
	$(MAKE) -f CMakeFiles/zia.dir/build.make CMakeFiles/zia.dir/sources/Server.cpp.i
.PHONY : sources/Server.cpp.i

sources/Server.s: sources/Server.cpp.s
.PHONY : sources/Server.s

# target to generate assembly for a file
sources/Server.cpp.s:
	$(MAKE) -f CMakeFiles/zia.dir/build.make CMakeFiles/zia.dir/sources/Server.cpp.s
.PHONY : sources/Server.cpp.s

sources/main.o: sources/main.cpp.o
.PHONY : sources/main.o

# target to build an object file
sources/main.cpp.o:
	$(MAKE) -f CMakeFiles/zia.dir/build.make CMakeFiles/zia.dir/sources/main.cpp.o
.PHONY : sources/main.cpp.o

sources/main.i: sources/main.cpp.i
.PHONY : sources/main.i

# target to preprocess a source file
sources/main.cpp.i:
	$(MAKE) -f CMakeFiles/zia.dir/build.make CMakeFiles/zia.dir/sources/main.cpp.i
.PHONY : sources/main.cpp.i

sources/main.s: sources/main.cpp.s
.PHONY : sources/main.s

# target to generate assembly for a file
sources/main.cpp.s:
	$(MAKE) -f CMakeFiles/zia.dir/build.make CMakeFiles/zia.dir/sources/main.cpp.s
.PHONY : sources/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... zia"
	@echo "... CgiModule"
	@echo "... PreParseRequest"
	@echo "... PostGenerateResponse"
	@echo "... PreConnexion"
	@echo "... ContentModule"
	@echo "... PostConnexion"
	@echo "... PostParseRequest"
	@echo "... sources/ConfParser.o"
	@echo "... sources/ConfParser.i"
	@echo "... sources/ConfParser.s"
	@echo "... sources/Logger.o"
	@echo "... sources/Logger.i"
	@echo "... sources/Logger.s"
	@echo "... sources/ModuleLoader.o"
	@echo "... sources/ModuleLoader.i"
	@echo "... sources/ModuleLoader.s"
	@echo "... sources/Server.o"
	@echo "... sources/Server.i"
	@echo "... sources/Server.s"
	@echo "... sources/main.o"
	@echo "... sources/main.i"
	@echo "... sources/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

